README.md
Noticed this was incorrect when trying to create a user.
=> To create an admin user, the key is 'va_admin', not 'admin'

app/assets/stylesheets/_vec.scss, app/views/veterans/_form.html.erb
Please review @gnakm, @emilyville or @ayaleloehr!
=> Add call out for job scams closes #97

app/views/veterans/_form.html.erb
Quick word change -- please check! @emilyville
=> Changed the word Veteran to Resume

app/views/static_pages/_linkedin.html.erb, app/views/static_pages/job_resources_partnered.html.erb
=> Change coursera links to surveymonkey

app/controllers/veterans_controller.rb
Fixes #98 
Code was trying to access attributes of nil object
=> Fix unknown MOC error

app/views/static_pages/for_job_seekers.html.erb, app/views/static_pages/job_resources_partnered.html.erb
=> Update American Job Center links

README.md
=> Adding instructions for making yourself a VA admin locally

app/views/veterans/_veteran.html.erb, app/views/veterans/show.html.erb
=> Remove star from favorite button

.gitignore, app/views/skills/index.html.erb
This is new content for the skills translator page (last paragraph).
@koconnor719 @ayaleloehr  Could you check this change?
=> Skills translator content

app/controllers/veterans_controller.rb, app/models/veteran.rb, app/views/veterans/index.html.erb, db/migrate/20160303173148_drop_alp_date.rb, spec/features/veteran_search_spec.rb
=> remove ALP field

app/controllers/veterans_controller.rb, spec/features/veteran_search_spec.rb
Fixes #143 
Need to use an inner join when restricting results via education and an outer join otherwise
=> Update veteran search query

README.md, app/models/user.rb, config/initializers/devise.rb
All references to GI Bill SAML are not actually used and should not exist in this repo.
=> Remove all references to GI Bill SAML

app/helpers/search_helper.rb, app/views/static_pages/job_search.html.erb
=> Remove final references to AddThis

app/assets/javascripts/veterans_new.js.erb, app/views/employers/index.html.erb, spec/features/employer_list_spec.rb, vendor/assets/javascripts/jquery.dataTables.js
- Update DataTables from 1.10.0 to 1.10.11
- Render company name as text
- Escape skills manually added
=> Properly escaping text input

config/environments/production.rb
=> Remove force_ssl

Gemfile, Gemfile.lock, app/controllers/veterans_controller.rb, app/models/veteran.rb, app/views/veterans/show.html.erb, app/views/veterans/word.docx.caracal, spec/features/veterans_access_spec.rb
Version 2.1 of resume download :)
Given enough time, I'd love to look more into the formatting and text, but submitting this as a good first update and looking in to federal resume next.
=> Resume updates

app/controllers/veterans_controller.rb, app/views/veterans/show.html.erb, app/views/veterans/word.docx.caracal, spec/features/veterans_access_spec.rb
Info on veteran's preference from: http://vaforvets.va.gov/docs/Resume_Building_Guide_01062012.pdf and https://www.fedshirevets.gov/job/vetpref/
list of required fields attached
[usajobs_resume_template.pdf](https://github.com/department-of-veterans-affairs/veterans-employment-center/files/186957/usajobs_resume_template.pdf)
=> Resume updates-update federal resume

app/views/layouts/application.html.erb
Need to remove vets.gov Google Analytics tag from va-common gem before merge.
=> Add google tag manager

app/models/employer.rb, app/views/employers/_form.html.erb, spec/models/employer_spec.rb
=> Duplicate EINs

app/assets/stylesheets/_vec.scss, app/views/employers/commitments.html.erb
I couldn't find the final copy for this one - I saw the link to https://github.com/department-of-veterans-affairs/vets-website/pull/1600 but this was confusing - so I just grabbed the first paragraph. 
We should revisit this guy soon, but all in all should work and is an improvement!!
=> add some new copy to commitments page and some number boxes

app/assets/stylesheets/_vec.scss
Bumping down font size, fixes #259 
Please review and merge
@gnakm @ayaleloehr or @cfeeney-va
=> bump it down to 2.5em

app/views/search/_advanced_search.html.erb, app/views/search/_featured_jobs.html.erb, app/views/search/_form.html.erb, app/views/search/_jobs.html.erb, app/views/search/_search_header.html.erb, app/views/search/search_jobs.html.erb, spec/features/job_search_spec.rb
heyohhhhh
yet another job search page - in case the other is not possible without many hours of work.
but with less surgery (and with less beautiful) 
Assigning to @cfeeney-va - search results aren't working for me but I have a feeling this might be my env because there aren't errors.
=> job search page light - where we don't move everything

app/reports/commitment_report.rb, app/views/employers/commitments.html.erb
Show date last updated for employer commitments
=> Show employer progress

app/views/static_pages/employers.html.erb, spec/features/employer_setup_spec.rb, spec/requests/employers_spec.rb
new copy and removed learned more on employers logged in page.
=> Employer log in take 2

app/assets/stylesheets/_vec.scss, app/views/static_pages/employers.html.erb, config/locales/devise.en.yml, spec/controllers/omniauth_callbacks_controller_spec.rb, spec/features/employer_setup_spec.rb, spec/requests/employers_spec.rb
=> Improve employer login

app/views/devise/sessions/new.html.erb, app/views/search/_featured_jobs.html.erb, app/views/search/_form.html.erb, app/views/static_pages/employers.html.erb, spec/features/job_search_spec.rb
A bunch of copy edits to employers, sign in page, and search page. 
Closes #283
=> Copy edits

app/views/search/_featured_jobs.html.erb, app/views/search/_featured_pagination.html.erb, app/views/search/search_jobs.html.erb, spec/features/job_search_spec.rb
=> Update look of job search

app/assets/stylesheets/_vec.scss, app/views/veterans/new.html.erb, app/views/veterans/show.html.erb
Pages look like this; feel free to critique.
=> Disable ds login and show message

app/assets/stylesheets/_vec.scss, app/views/veterans/new.html.erb, app/views/veterans/show.html.erb
This reverts commit 522afb6faa30923beb4cf827544cc8874a93b8f8.
=> Revert "Disable ds login and show message (#295)"

app/views/search/_form.html.erb, app/views/static_pages/_jobsearch.html, config/routes.rb
Changing underscore to dash to get URL consistency.
=> change search_jobs to search-jobs

app/controllers/application_controller.rb
Fixing issue identified by brakeman. Logging in still worked locally when I tested it (old comment said there was a bug with that). Should still test in staging as well to be sure this doesn't break anything else.
=> Add throwing CSRF exception

app/controllers/veterans_controller.rb, app/views/veterans/_form.html.erb
=> Fix skills saving

config/application.rb
Matches roadrunner-rails [PR56](https://github.com/department-of-veterans-affairs/roadrunner-rails/pull/56)
=> Gzip content when possible

app/assets/javascripts/skill_translator.js.erb, app/controllers/skills_controller.rb, app/models/military_occupation.rb, app/views/skills/index.html.erb
This reverts commit 4714d1bc05f13dc0c691c18253cd68b531855693.
=> Revert "Add moc filters (#296)"

config/puma.rb
Also going to increase the connection pool count to match this number of threads. PTAL @orischwartz
=> Update puma configs

app/views/layouts/application.html.erb
=> DAP code is already in VEC via the va_common gem

app/controllers/veterans_controller.rb, app/views/veterans/new.html.erb, spec/features/veterans_access_spec.rb, spec/features/veterans_spec.rb
Also remove ability for logged in employers to create resumes.
=> Fix bug allowing URL access to profiles

app/views/search/_advanced_search.html.erb
Zip code searching didn't actually function, so removing it from the UI
=> Remove zip code in advanced search

app/views/static_pages/employers.html.erb
This makes the cards look like all the others!
=> make employer cards 2 up instead of 3 up now that there are only two

app/assets/stylesheets/_vec.scss, app/helpers/form_helper.rb, app/views/skills/index.html.erb, app/views/veterans/_form.html.erb
This branch implements USA Standard error states as shown below.
Resume builder:
Skills Translator is an Angular app...
=> Use USA Standard error states

Gemfile, Gemfile.lock, app/assets/stylesheets/_dataTable-overrides.scss, app/assets/stylesheets/application.scss
Resolves https://github.com/department-of-veterans-affairs/vets-website/issues/2692
=> Use USWDS styles for standard tables

app/views/layouts/word.html.erb
closes department-of-veterans-affairs/vets-website#2674
=> replaces helvetica with source sans pro

app/assets/stylesheets/_vec.scss, app/views/employers/commitments.html.erb, app/views/search/_form.html.erb
Resolves https://github.com/department-of-veterans-affairs/vets-website/issues/2694
=> Unify sidebar styling

Gemfile, Gemfile.lock, config/environments/production.rb
One last thing - noticed logging was not happening in staging. Can't in good conscience push that to prod. This follows log configuration approach used in all other apps.
=> Fix stdout logging

app/views/employers/_commitment_summary.html.erb
* Comma separate 'Special commitments to'.
=> production merge 2017-06-13

Jenkinsfile.deploy
adds fix for [#4505](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4505) for this repo
=> add pip upgrade to jenkinsfile
