department-of-veterans-affairs/veterans-employment-center

- app/assets/stylesheets/_vec.scss
The text in the submit button on the resume builder was being cut off on small screens. I just added `white-space: normal` to the styles so that the text inside the button will wrap. Please review @emilyville!
> Add text wrapping to resume builder submit button resolves #62

- app/views/veterans/_form.html.erb
Remove add another skill link as you can add skills by pressing enter (specified in label). Still need to adjust hover styling, but cannot do it locally because my database isn't seeded with any skills yet. Waiting to hear back from @ayaleloehr on that, so I will create a new issue to address the hover styling in the meantime. 
Please review @gnakm and @emilyville!
> Remove add another skill link closes #45

- app/views/layouts/application.html.erb
Fixes #94 
Trying to load the favicon was throwing a 404 error, which was trying to redirect to the vets.gov 404 page which then threw a 403 error.  After some research, the issue has to do with the rails asset pipeline; the favicon is a precompiled asset in production and the code wasn't looking in the right place (let me know if you want a more detailed explanation and/or directions on how to test locally).
> Update path for favicon

- app/views/static_pages/_linkedin.html.erb
This is for Issue #65 
Instead of adding the Coursera logo, we are removing the Linkedin logo.
@ayaleloehr please review!
> Removed linkedin logo from Job Seekers page

- app/assets/javascripts/veterans_new.js.erb
- app/assets/stylesheets/skills_translator.scss
- app/views/veterans/_form.html.erb
Fixes #81 
Replaced trashcan icon with "- delete" link.  Per conversation in #81, this is preferred to icons and is better for accessibility.  I also like the consistency with the "+ Add Experience" links.
> Replace trashcan icons with delete link

- config/initializers/devise.rb
Google OAuth requests inexplicably started returning with `JWT::InvalidIatError: Invalid iat` errors without this change.
> add skip_jwt to google OAuth commands

- app/controllers/veterans_controller.rb
File was downloading as `veterans.csv.csv` because StreamCSV automatically puts a `.csv` on the end.  This will cause the document to properly download as `veterans.csv` now.
> Remove duplicate ".csv" from downloaded file

- app/assets/javascripts/employers_edit.js.erb
- app/models/employer.rb
- app/views/employers/_form.html.erb
- spec/factories/factories.rb
- spec/features/employer_setup_spec.rb
- spec/features/resume_spec.rb
- spec/models/employer_spec.rb
Addresses two requested validations:
1) Hiring commitment should be greater than or equal to one
2) EIN should be 9 characters long (originally requested in #131 )
Final validation on EIN (no duplicates) will be addressed in separate task.
Let me know if you have any questions!
Discussed design somewhat with Gina but we could still run the final product by her...ping me if you want me to add screenshots.
> Enforce validation on select fields on employer edit page

- app/views/veterans/_form.html.erb
- app/views/veterans/new.html.erb
- spec/features/veterans_access_spec.rb
- spec/features/veterans_spec.rb
update for tomorrow!
I don't know why the same or similar text blocks are on this page twice for logged in/not logged in? But I am not addressing that here! 
should look like this:
> update resume page with careers and employment changes

- app/views/employers/commitments.html.erb
- app/views/employers/edit.html.erb
- app/views/employers/index.html.erb
- app/views/employers/show.html.erb
- app/views/layouts/_navigation.html.erb
- app/views/layouts/application.html.erb
- app/views/static_pages/employers.html.erb
- app/views/static_pages/home.html.erb
- app/views/veterans/favorites.html.erb
- app/views/veterans/index.html.erb
- spec/features/employer_setup_spec.rb
- spec/features/resume_spec.rb
- spec/requests/employers_spec.rb
- spec/requests/static_pages_spec.rb
- spec/requests/veterans_spec.rb
Remove duplicated employer actions from nav bar.  Move navbar to the bottom of the vets.gov banner
> Update nav bar

- app/views/static_pages/employers.html.erb
This PR looks like more changes than it really is. Added Post a Job card to the employer landing page when not logged in and reordered the cards for when an employer is logged in so that the cards that were there prior to login are still in the same place (consistent UX). And fixing much indenting.
> Post a Job shows up when not logged in (and reordering cards)

- app/views/employers/index.html.erb
- app/views/veterans/_form.html.erb
Addresses https://github.com/department-of-veterans-affairs/vets-website/issues/2676
- Use button tags over input[submit] for consistent visual style
@crwallace  Please review:
This is a temporary fix for these separate apps. All submit buttons now have rounded corners corresponding to the US web standard style buttons. Essentially using a `<button>` instead of `input type=submit` is both more semantically correct and also fixes the style issues with `input type=submit` inheriting from Foundation css styles in the VA Common gem.
Ideally once all of the apps use a unified stylesheet (and most of the Foundation styles are removed?) we will be much closer to parity with US Web Standard Style
> Addresses issue #2676 US web standard style for all buttons

- app/assets/stylesheets/_vec.scss
Temporary fix for CTA buttons. We can probably get away from having specific CSS like this once we slowly migrate off of Foundation 
https://github.com/department-of-veterans-affairs/va_common/pull/40
> Fix CTA color on secondary buttons

- app/views/skills/index.html.erb
- Branch of Service: Army
- Moc code: b12
I need to do a lot more digging into the code to understand the data shapes and Skills Translator, but this should fix the issue of the error message for "invalid MOC".  This brings the validation to parity with what was in place before we switched to using USWDS error states.
FYI the skills translator is an Angular app
> Fix MOC validations on Skills Translator

- app/controllers/skills_controller.rb
Addresses an issue causing processes to hang during skills translator queries.
Visiting https://staging.vets.gov/employment/job-seekers/skills-translator and using Army 12B causes a number of `{ id => nil, relevance => 1.0, name => nil, weight => 1.0 }` skills to be filtered by the randomization functions. The randomization expected a unique set of values, and wouldn't exit a loop properly when non-uniques were presented. The result was a request that timed out when the ELB killed it ~60s in.
There may be other similar behavior causing issues in production, and we're addressing logging and monitoring to help debug them there.
> Allow exiting loop when duplicate skills exist

- app/controllers/users/omniauth_callbacks_controller.rb
- spec/controllers/omniauth_callbacks_controller_spec.rb
We're seeing this error pop up in production with new relic's exception tracking:
```
NoMethodError: undefined method `persisted?' for nil:NilClass
…app/controllers/users/omniauth_callbacks_controller.rb:   24:in `linkedin'
```
It's occurring during the [linkedin oauth](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/app/controllers/users/omniauth_callbacks_controller.rb#L17), and as far as I can tell is either the result of no email being provided from linkedin, or a uid that's already associated with another email address. 
A quick fix would be using `if @user && @user.persisted?` instead of `if @user.persisted` on L24, but that may just hide the issue.
Has this already been investigated?
> undefined method `persisted?' for nil:NilClass

- lib/jobs_api.rb
- spec/lib/jobs_api_spec.rb
We've experienced issues with hanging requests to the Heroku-based Jobs API. The ELB we've configured for VEC will return a timeout to the client after 60s. It doesn't appear that the Jobs API is undergoing any performance difficulties for these requests, though more in depth investigation may be required. This (somewhat hacky) solution will
* Add a default timeout of 3 seconds to the Jobs API request
* Retry a request to the Jobs API on timeout (once)
in the hopes of providing a more consistent and performant experience to the user.
Further investigation into the cause is on hold until the Jobs API is migrated into GC (https://github.com/department-of-veterans-affairs/devops/issues/570)
> Retry requests to Jobs API on timeout

- app/controllers/users/omniauth_callbacks_controller.rb
- lib/jobs_api.rb
- spec/controllers/omniauth_callbacks_controller_spec.rb
- spec/lib/jobs_api_spec.rb
This release contains additional logging information for oauth failures that cause 500's and associated alerts, as well as a retry mechanism and timeouts for requests to the jobs API that cause ELB-5XX alerts.
> Production Release Sept 1, 2016

- lib/jobs_api.rb
- lib/retriable_search_request.rb
- lib/us_jobs_search.rb
- spec/lib/retriable_search_request_spec.rb
- spec/lib/us_jobs_search_spec.rb
We've been seeing a number of timeout issues with the US Jobs Search API requests. This PR involves using the same logic for the Jobs API requests, setting an explicit timeout and attempting to retry.
> Timeout and retry for US Jobs Search

- README.md
- db/migrate/20170112043901_add_skills_is_common_index.rb
- db/schema.rb
Fixes issue observed in production: https://github.com/department-of-veterans-affairs/devops/issues/873
We have not seen this VEC issue re-occur, and there is little harm in adding a column index. The skills table is is used by resume-builder and so will live on for a while at least.
Verified that db:migrate is happy even if the index by the same name already exists, as is the case in production.
> Add index on skills is_common

- Gemfile
- Gemfile.lock
- Jenkinsfile
- README.md
Fixes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/897
VEC is not doing any special exception handling, so relying on Sentry's default Rails integration which will capture all uncaught exceptions if SENTRY_DSN is set, which we are doing in devops with: https://github.com/department-of-veterans-affairs/devops/pull/1394
> Pv add sentry

- app/views/employers/_commitment_summary.html.erb
Resolves department-of-veterans-affairs/vets.gov-team#3097.
I wasn't able to test it since the table wasn't populated with any companies when I tried to check locally. Not sure if I missed a step in setup.
In any case, since `employer.commitment_categories` appears to be an array, I believe this change should be all that's required.
> Comma separate 'Special commitments to'.

- app/views/layouts/application.html.erb
Replaces the old, VEC-specific GTM container `GTM-5KBL3T` with the new, Vets.gov-wide container `GTM-WFJWBD`
The old container was setup to report only basic pageviews, which the new container also has so reported data should remain the same across the switch.
This a debt clean-up to finish the consolidation of our analytics config.
> Replace old VEC GTM Container with Vets-wide container ID

- Gemfile.lock
This is the most recent version on the sentry gem. This pr should only be merged after we upgrade our sentry server.
> upgrade sentry gem
